# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'lab7' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Database' , '~> 4.0'
  pod 'Firebase/Auth'
  pod 'GeoFire', :git => 'https://github.com/firebase/geofire-objc.git'

  # Pods for lab7

  target 'lab7Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'lab7UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end



